# Use macos-15 image (beta) with XCode 16.x and Swift 6.x installed
# https://github.com/actions/runner-images/issues/10686
# MacOS image reference: https://github.com/actions/runner-images/tree/main/images/macos
name: Swift Build

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  swift:
    defaults:
      run:
        working-directory: ./swiftpm-lib
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - name: Xcode versions
        run: |
          xcode-select -p
          pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
      - name: Swift versions
        run: |
          xcrun swift --version
          swift --version

  swift-build:
    defaults:
      run:
        working-directory: ./swiftpm-lib
    needs: swift
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - run: make all

  swift-test:
    defaults:
      run:
        working-directory: ./swiftpm-lib
    needs: swift
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - run: make all
      - run: make test
